steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone','https://github.com/SamFangshan/Virtual-Hospital.git']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}','.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}']

- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'env'
  - 'deployment/${_DEPLOYMENTNAME}'
  - 'STRIPE_API_KEY=${_STRIPE_API_KEY}'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'

- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'env'
  - 'deployment/${_DEPLOYMENTNAME}'
  - 'PG_USER=${_PG_USER}'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'

- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'env'
  - 'deployment/${_DEPLOYMENTNAME}'
  - 'PG_PASSWORD=${_PG_PASSWORD}'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'

- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'env'
  - 'deployment/${_DEPLOYMENTNAME}'
  - 'PG_HOST=${_PG_HOST}'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'

- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'env'
  - 'deployment/${_DEPLOYMENTNAME}'
  - 'PG_PORT=${_PG_PORT}'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'

- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'env'
  - 'deployment/${_DEPLOYMENTNAME}'
  - 'PG_DATABASE=${_PG_DATABASE}'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'

- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/${_DEPLOYMENTNAME}'
  - '${_CONTAINERNAME}=gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'

- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'rollout'
  - 'restart'
  - 'deployment'
  - '${_DEPLOYMENTNAME}'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'

substitutions:
    _VERSION: v1.0

options:
    substitution_option: 'ALLOW_LOOSE'
