steps:
# Clone source code from GitHub
- name: 'gcr.io/cloud-builders/git'
  args: ['clone','https://github.com/SamFangshan/Virtual-Hospital.git']

# Python test
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['init']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['auth', 'login']

- name: alpine:3
  entrypoint: sh
  args:
    - '-c'
    - 'wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy && chmod +x cloud_sql_proxy && ./cloud_sql_proxy -instances=${_DB_INSTANCE_NAME}=tcp:3306'

- name: 'docker.io/library/python:3.7'
  args: ['pip', 'install', '-t', '/workspace/lib', '-r', 'requirements.txt']

- name: 'docker.io/library/python:3.7'
  args: ['python', '-m', 'pytest']
  env:
  - 'PYTHONPATH=/workspace/lib:.'
  - 'PG_USER=${_PG_USER}'
  - 'PG_PASSWORD=${_PG_PASSWORD}'
  - 'PG_HOST=localhost'
  - 'PG_PORT=3306'
  - 'TEST_PG_DATABASE=${_TEST_PG_DATABASE}'


# Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}','.']

# Push Docker image to GCS
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}']

# Environment set-up
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'env'
  - 'deployment/${_DEPLOYMENTNAME}'
  - 'STRIPE_API_KEY=${_STRIPE_API_KEY}'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'

- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'env'
  - 'deployment/${_DEPLOYMENTNAME}'
  - 'PG_USER=${_PG_USER}'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'

- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'env'
  - 'deployment/${_DEPLOYMENTNAME}'
  - 'PG_PASSWORD=${_PG_PASSWORD}'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'

- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'env'
  - 'deployment/${_DEPLOYMENTNAME}'
  - 'PG_HOST=${_PG_HOST}'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'

- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'env'
  - 'deployment/${_DEPLOYMENTNAME}'
  - 'PG_PORT=${_PG_PORT}'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'

- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'env'
  - 'deployment/${_DEPLOYMENTNAME}'
  - 'PG_DATABASE=${_PG_DATABASE}'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'

# Update image on GKE Deployment
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/${_DEPLOYMENTNAME}'
  - '${_CONTAINERNAME}=gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'

# Restart GKE Deployment
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'rollout'
  - 'restart'
  - 'deployment'
  - '${_DEPLOYMENTNAME}'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'

substitutions:
    _VERSION: v1.0

options:
    substitution_option: 'ALLOW_LOOSE'
